#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/src/server/index.php';
require __DIR__ . '/src/logHandler.php';

$envFilePath = '.env';

$logHandler = new LogHandler();
$logHandler->addErrorLogWarning('Foo');
$logHandler->addErrorLogError('Bar');

$server = new PHPServer($envFilePath);
$server->startServer();
